update

diff --git a/now b/now
--- a/now
+++ b/now
@@ -1,11 +1,9 @@
 #!/bin/bash
-set -eu
+set -eux
 
-if ! test -f $(which curl)
-then
-    echo "curl is not installed"
-    exit
-fi
+
+# script will fail if it's not installed
+which curl > /dev/null
 
 curl -s https://github.com/kmille/dotfiles/blob/master/bash_aliases -o ~/.bash_aliases_chs
 curl -s https://github.com/kmille/dotfiles/blob/master/vimrc -o ~/.vimrc
